[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
default_section = "THIRDPARTY"
known_first_party = "feesprefect"
known_third_party = ["decouple", "django"]

[tool.black]
line-length = 88
include = '\.pyi?$'
# exclude = "[a-zA-Z]*/(migrations)/(.)*"

[tool.pylint.format]
max-line-length = "88"

[tool.pylint.MESSAGE_CONTROL]
disable = """
    line-too-long,
    abstract-method,
    no-member,
"""
