[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
default_section = "THIRDPARTY"
known_first_party = "feesprefect"
known_third_party = ["decouple", "django", "django_stubs_ext", "djmoney", "import_export", "moneyed"]

[tool.black]
line-length = 88
include = '\.pyi?$'
# exclude = "[a-zA-Z]*/(migrations)/(.)*"

[tool.pylint.format]
max-line-length = "88"

[tool.pylint.MESSAGE_CONTROL]
disable = """
    line-too-long,
    abstract-method,
    no-member,
"""

# [tool.mypy]
# plugins = ["mypy_django_plugin.main"]
# mypy_path = "venv/lib/python3.9/site-packages"

# [tool.django-stubs]
# django_settings_module = "feesprefect.settings.local"

# [tool.mypy-djmoney.*]
# ignore_missing_imports = "True"
