# Generated by Django 3.2.16 on 2022-12-14 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feesprefectadmin',
            options={'verbose_name': 'Feesprefect Admin', 'verbose_name_plural': 'Feesprefect Admins'},
        ),
    ]
