# Generated by Django 3.2.16 on 2023-03-30 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolfee',
            name='term',
        ),
    ]
