# Generated by Django 3.2.16 on 2023-04-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_student_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='student',
            name='home_address',
            field=models.TextField(blank=True, null=True, verbose_name='Home Address'),
        ),
        migrations.AddField(
            model_name='student',
            name='name_of_guardian',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Parent/Guardian'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number_of_guardian',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone Number of Parent/Guardian'),
        ),
    ]
