# Generated by Django 3.2.16 on 2023-07-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20230427_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolfeespayment',
            name='is_registration_fee_payment',
            field=models.BooleanField(default=False, verbose_name='Is Registration Fee Payment?'),
        ),
    ]
